#!/usr/bin/env bash
# =============================================================================
# sync.sh — Claude Code → Antigravity Global Convention Sync
# =============================================================================
# Syncs ALL Claude Code conventions to Antigravity across every project.
# Place at: ~/.claude/sync/sync.sh
# Run manually: bash ~/.claude/sync/sync.sh
# Or let the watcher (watch.sh) call it automatically.
# =============================================================================

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; DIM='\033[2m'; RESET='\033[0m'
BOLD='\033[1m'

log()    { echo -e "${DIM}[$(date +%H:%M:%S)]${RESET} $1"; }
ok()     { echo -e "${GREEN}✓${RESET} $1"; }
warn()   { echo -e "${YELLOW}⚠${RESET} $1"; }
info()   { echo -e "${BLUE}→${RESET} $1"; }
header() { echo -e "\n${BOLD}${CYAN}$1${RESET}"; }

# ── Paths ─────────────────────────────────────────────────────────────────────
CLAUDE_GLOBAL="$HOME/.claude"
ANTIGRAVITY_GLOBAL="$HOME/.gemini"
ANTIGRAVITY_BRAIN="$ANTIGRAVITY_GLOBAL/brain"
ANTIGRAVITY_RULES="$ANTIGRAVITY_GLOBAL/rules"
SKILLS_INDEX="$ANTIGRAVITY_BRAIN/_skills-index.md"

# Projects root — scans for dirs containing .claude/
# Add more roots to PROJECT_ROOTS if your projects are elsewhere
PROJECT_ROOTS=(
  "$HOME/Desktop"
  "$HOME/Projects"
  "$HOME/Developer"
  "$HOME/workspace"
)

# ── Mode ──────────────────────────────────────────────────────────────────────
# Optional: pass --project /path/to/project to sync a single project only
SINGLE_PROJECT=""
VERBOSE=false
for arg in "$@"; do
  case "$arg" in
    --project=*) SINGLE_PROJECT="${arg#*=}" ;;
    --project)   shift; SINGLE_PROJECT="${1:-}" ;;
    --verbose|-v) VERBOSE=true ;;
  esac
done

# ── Helpers ───────────────────────────────────────────────────────────────────
copy_if_changed() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  if [[ ! -f "$dst" ]] || ! diff -q "$src" "$dst" &>/dev/null; then
    cp "$src" "$dst"
    $VERBOSE && ok "  Copied $(basename "$src") → $dst"
    return 0
  fi
  $VERBOSE && log "  Unchanged: $(basename "$src")"
  return 1
}

sync_dir() {
  local src_dir="$1" dst_dir="$2" count=0
  mkdir -p "$dst_dir"
  if [[ -d "$src_dir" ]]; then
    while IFS= read -r -d '' file; do
      rel="${file#$src_dir/}"
      if copy_if_changed "$file" "$dst_dir/$rel"; then
        (( count++ )) || true
      fi
    done < <(find "$src_dir" -name "*.md" -type f -print0 2>/dev/null)
  fi
  echo "$count"
}

# =============================================================================
# GLOBAL SYNC — ~/.claude → ~/.gemini
# =============================================================================
sync_global() {
  header "◆ Global sync (~/.claude → ~/.gemini/brain)"

  mkdir -p "$ANTIGRAVITY_BRAIN" "$ANTIGRAVITY_RULES"
  local changed=0

  # 1. CLAUDE.md → global brain
  if [[ -f "$CLAUDE_GLOBAL/CLAUDE.md" ]]; then
    copy_if_changed "$CLAUDE_GLOBAL/CLAUDE.md" "$ANTIGRAVITY_BRAIN/CLAUDE.md" && (( changed++ )) || true
    ok "CLAUDE.md"
  else
    warn "No ~/.claude/CLAUDE.md found — skipping global context"
  fi

  # 2. Rules → brain/rules/
  if [[ -d "$CLAUDE_GLOBAL/rules" ]]; then
    count=$(sync_dir "$CLAUDE_GLOBAL/rules" "$ANTIGRAVITY_BRAIN/rules")
    ok "Rules  ($count files synced)"
  fi

  # 3. Skills → build a Skills Index for Antigravity
  # Antigravity can't auto-discover .claude/skills/, so we build a single
  # _skills-index.md that references all skills with their descriptions + content.
  sync_global_skills

  # 4. Commands → brain/commands/ (so Antigravity treats them as workflows)
  if [[ -d "$CLAUDE_GLOBAL/commands" ]]; then
    count=$(sync_dir "$CLAUDE_GLOBAL/commands" "$ANTIGRAVITY_BRAIN/commands")
    ok "Commands  ($count files)"
  fi

  # 5. settings.json — extract deny-list entries for Antigravity
  if [[ -f "$CLAUDE_GLOBAL/settings.json" ]]; then
    extract_deny_list "$CLAUDE_GLOBAL/settings.json" "$ANTIGRAVITY_BRAIN/deny-list.md"
    ok "Deny list  (extracted from settings.json)"
  fi

  echo ""
  info "Global sync done."
}

# Build a flat skills index so Antigravity auto-loads all skills in one KI
sync_global_skills() {
  local skills_dir="$CLAUDE_GLOBAL/skills"
  [[ -d "$skills_dir" ]] || return 0

  local index_content="# Claude Skills Index\n"
  index_content+="<!-- Auto-generated by sync.sh — do not edit manually -->\n\n"
  index_content+="The following skills are available. Apply them when relevant.\n\n"

  local skill_count=0
  while IFS= read -r -d '' skill_file; do
    local skill_name
    skill_name=$(basename "$(dirname "$skill_file")")
    index_content+="---\n\n"
    index_content+="## Skill: $skill_name\n\n"
    index_content+=$(cat "$skill_file")
    index_content+="\n\n"
    (( skill_count++ )) || true
  done < <(find "$skills_dir" -name "SKILL.md" -type f -print0 2>/dev/null)

  if (( skill_count > 0 )); then
    mkdir -p "$(dirname "$SKILLS_INDEX")"
    printf "%b" "$index_content" > "$SKILLS_INDEX"
    ok "Skills  ($skill_count skills indexed → _skills-index.md)"
  fi
}

# Extract denyCommands from settings.json into a readable KI for Antigravity
extract_deny_list() {
  local settings_file="$1" output="$2"
  if command -v python3 &>/dev/null; then
    python3 - "$settings_file" "$output" <<'EOF'
import json, sys
try:
    with open(sys.argv[1]) as f:
        s = json.load(f)
    denied = s.get("permissions", {}).get("denyCommands", [])
    if not denied:
        sys.exit(0)
    lines = ["# Deny list\n", "<!-- Synced from ~/.claude/settings.json -->\n\n"]
    lines.append("The following shell commands are FORBIDDEN and must never be run:\n\n")
    for cmd in denied:
        lines.append(f"- `{cmd}`\n")
    with open(sys.argv[2], "w") as f:
        f.writelines(lines)
except Exception as e:
    print(f"Warning: Could not extract deny list: {e}", file=sys.stderr)
EOF
  fi
}

# =============================================================================
# PROJECT SYNC — .claude/ → .gemini/antigravity/brain/  (single project)
# =============================================================================
sync_project() {
  local project_dir="$1"
  local claude_dir="$project_dir/.claude"
  local ag_brain="$project_dir/.gemini/antigravity/brain"
  local ag_workflows="$project_dir/.agents/workflows"

  [[ -d "$claude_dir" ]] || return 0

  local project_name
  project_name=$(basename "$project_dir")
  info "Syncing project: ${BOLD}$project_name${RESET}"

  mkdir -p "$ag_brain" "$ag_workflows"
  local total=0

  # CLAUDE.md (project root, not in .claude/)
  if [[ -f "$project_dir/CLAUDE.md" ]]; then
    copy_if_changed "$project_dir/CLAUDE.md" "$ag_brain/CLAUDE.md" && (( total++ )) || true
  fi

  # .claude/rules/ → brain/rules/
  if [[ -d "$claude_dir/rules" ]]; then
    count=$(sync_dir "$claude_dir/rules" "$ag_brain/rules")
    (( total += count )) || true
  fi

  # .claude/commands/ → brain/commands/ AND .agents/workflows/
  if [[ -d "$claude_dir/commands" ]]; then
    count=$(sync_dir "$claude_dir/commands" "$ag_brain/commands")
    sync_dir "$claude_dir/commands" "$ag_workflows" > /dev/null
    (( total += count )) || true
  fi

  # .claude/skills/ — build per-project skills index
  if [[ -d "$claude_dir/skills" ]]; then
    local pskills_index="$ag_brain/_skills-index.md"
    local skill_count=0
    local index_content="# Project Skills Index\n<!-- Auto-generated by sync.sh -->\n\n"
    while IFS= read -r -d '' skill_file; do
      local skill_name
      skill_name=$(basename "$(dirname "$skill_file")")
      index_content+="---\n\n## Skill: $skill_name\n\n"
      index_content+=$(cat "$skill_file")
      index_content+="\n\n"
      (( skill_count++ )) || true
    done < <(find "$claude_dir/skills" -name "SKILL.md" -type f -print0 2>/dev/null)
    if (( skill_count > 0 )); then
      printf "%b" "$index_content" > "$pskills_index"
      (( total += skill_count )) || true
    fi
  fi

  # .claude/settings.json — extract deny list
  if [[ -f "$claude_dir/settings.json" ]]; then
    extract_deny_list "$claude_dir/settings.json" "$ag_brain/deny-list.md"
    (( total++ )) || true
  fi

  if (( total > 0 )); then
    ok "  $project_name  ($total items synced)"
  else
    $VERBOSE && log "  $project_name  (nothing changed)"
  fi
}

# =============================================================================
# SCAN ALL PROJECTS
# =============================================================================
sync_all_projects() {
  header "◆ Project sync (scanning all project roots)"

  local found=0
  for root in "${PROJECT_ROOTS[@]}"; do
    [[ -d "$root" ]] || continue
    while IFS= read -r -d '' project; do
      sync_project "$project"
      (( found++ )) || true
    done < <(find "$root" -maxdepth 3 -name ".claude" -type d -print0 2>/dev/null \
             | sed -z 's|/.claude$||')
  done

  # Also scan git repos in home that aren't under PROJECT_ROOTS
  while IFS= read -r -d '' project; do
    # Skip if already covered by project roots
    local already=false
    for root in "${PROJECT_ROOTS[@]}"; do
      [[ "$project" == "$root"* ]] && already=true && break
    done
    $already && continue
    [[ -d "$project/.claude" ]] || continue
    sync_project "$project"
    (( found++ )) || true
  done < <(find "$HOME" -maxdepth 4 -name ".git" -type d -print0 2>/dev/null \
           | sed -z 's|/.git$||')

  if (( found == 0 )); then
    warn "No projects with .claude/ found under: ${PROJECT_ROOTS[*]}"
    info "Tip: Add your projects root to PROJECT_ROOTS in sync.sh"
  else
    info "$found project(s) scanned."
  fi
}

# =============================================================================
# MAIN
# =============================================================================
main() {
  echo -e "${BOLD}${CYAN}"
  echo "  Claude Code → Antigravity Sync"
  echo -e "${RESET}"

  sync_global

  if [[ -n "$SINGLE_PROJECT" ]]; then
    header "◆ Single project sync"
    sync_project "$SINGLE_PROJECT"
  else
    sync_all_projects
  fi

  echo ""
  echo -e "${GREEN}${BOLD}Done.${RESET} All Claude conventions synced to Antigravity."
}

main "$@"
